name: CI Backend

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test_backend:
    name: Unit tests (area-backend)
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: area-backend
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: area-backend/package.json

      - name: Install dependencies
        run: npm ci

      - name: Run unit tests
        run: npm test --silent

  build_backend:
    name: Build (area-backend)
    runs-on: ubuntu-latest
    needs: test_backend
    if: |
      (github.event_name == 'push' && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/dev')) ||
      (github.event_name == 'pull_request' && (github.base_ref == 'main' || github.base_ref == 'dev'))
    defaults:
      run:
        working-directory: area-backend
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: area-backend/package.json

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build
